import { Inter } from 'next/font/google'
import './globals.css'
import Provider from './SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/authoptions'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang='en'>
      <body>
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  )
}
